# Cloud Build configuration for i18n-l10n app
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/i18n-l10n-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/i18n-l10n-app']
  

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/i18n-l10n-app'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
